// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgLlmBot.DataAccess;

#nullable disable

namespace TgLlmBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260904203827_AddReplyToQuoteText")]
    partial class AddReplyToQuoteText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbChatLimit", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatId"));

                    b.Property<int>("Limit")
                        .HasColumnType("integer");

                    b.HasKey("ChatId");

                    b.ToTable("ChatLimits");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<string>("Caption")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomPromptScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("CustomPromptUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromFirstName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FromLastName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FromUsername")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsLlmReplyToMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaGroupId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int?>("MessageThreadId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReplyToMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("ReplyToQuoteText")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Text")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "Date")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_chathistory_chatid_date_desc");

                    b.HasIndex("ChatId", "MediaGroupId")
                        .HasDatabaseName("idx_chathistory_chatid_mediagroupid")
                        .HasFilter("\"MediaGroupId\" IS NOT NULL");

                    b.HasIndex("MessageId", "ChatId")
                        .HasDatabaseName("idx_chathistory_messageid_chatid");

                    b.HasIndex("ChatId", "MessageId", "Date")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_chathistory_chatid_messageid_date");

                    b.ToTable("ChatHistory");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbChatMessageMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("ChatMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("DownloadFileId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Emoji")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FileUniqueId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsAnimated")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("SetName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ThumbnailFileId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FileUniqueId")
                        .HasDatabaseName("idx_chatmessagemedia_fileuniqueid");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_chatmessagemedia_status");

                    b.HasIndex("ChatMessageId", "Order")
                        .HasDatabaseName("idx_chatmessagemedia_chatmessageid_order");

                    b.ToTable("ChatMessageMedia");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbChatSystemPrompt", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChatId"));

                    b.Property<string>("Prompt")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("ChatId");

                    b.ToTable("ChatSystemPrompts");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbChatUsage", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Used")
                        .HasColumnType("integer");

                    b.HasKey("Date", "ChatId", "UserId");

                    b.HasIndex("Date");

                    b.ToTable("Usage");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbKickedUser", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ChatId", "UserId");

                    b.ToTable("KickedUsers");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbMediaDescription", b =>
                {
                    b.Property<string>("FileUniqueId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("boolean");

                    b.HasKey("FileUniqueId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_mediadescriptions_createdat");

                    b.ToTable("MediaDescriptions");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbPersonalChatSystemPrompt", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prompt")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.HasKey("ChatId", "UserId");

                    b.ToTable("PersonalChatSystemPrompts");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbUserLimit", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Limit")
                        .HasColumnType("integer");

                    b.HasKey("ChatId", "UserId");

                    b.ToTable("Limits");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbChatMessageMedia", b =>
                {
                    b.HasOne("TgLlmBot.DataAccess.Models.DbChatMessage", "Message")
                        .WithMany("Media")
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TgLlmBot.DataAccess.Models.DbChatMessage", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
